# Generated by Django 5.2.8 on 2026-01-29 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_roll_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
