# Generated by Django 5.2.8 on 2026-01-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('organizer_name', models.CharField(max_length=100)),
                ('poster', models.ImageField(upload_to='event_posters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
