# Generated by Django 5.2.8 on 2026-01-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_event_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='Student', max_length=20),
            preserve_default=False,
        ),
    ]
