# Generated by Django 5.2.8 on 2026-02-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
