# Generated by Django 5.2.8 on 2026-02-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(default='TEMP', max_length=20),
            preserve_default=False,
        ),
    ]
